# Generated by Django 4.0.dev20210210185711 on 2021-03-23 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20210221_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='faculty_Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='comments',
        ),
    ]
